### ISSUE TITLE
Cannot build vite project using clarity core v6

### ISSUE THREAD

**Issue by wghglory** [vmware-clarity/core#100]
## Describe the bug  

I'm using Vite Vue and React both. After installing @cds/core @cds/react v6.0.0 and importing a clarity button component for example, the vite project build always raises the below error. Only when I downgrade clarity to 5.6.4, the below issue disappear. 

[vite]: Rollup failed to resolve import "@cds/core/icon/shapes/exclamation-circle.js" from "node_modules/@cds/core/forms/register.js". This is most likely unintended because it can break your application at runtime. If you do want to externalize this module explicitly add it to `build.rollupOptions.external` error during build:

## Versions  

**Clarity project:**  

- [x] Clarity Core
- [ ] Clarity Angular/UI  

**Clarity version:**  

- [ ] v5.x 
- [x] v6.x  

**Framework:**  

- [ ] Angular 
- [x] React 
- [x] Vue 
- [ ] Other:  

**Framework version:** 

Vite

**Comment by bbogdanov** [comment]
Just curious - are you using micro  front-end architecture?

**Comment by wghglory** [comment]
Not in this bug report. Just Vite + react/vue

**Comment by wghglory** [comment]
Yes, you can use this branch "issue/clarity" https://github.com/wghglory/vmware-vite-react-seed/tree/issue/clarity. In this branch, clarity version is 6.0.1. `npm run build` will see the build error. Only when downgrading to 5.6.4, the error disappears.

**Comment by ashleyryan** [comment]
I'm looking back at this again and that repo is react, I thought you said the issue was with vue? Do you have a smaller reproduction case - there's an awful lot of code in that repo and I don't have a lot of experience with Vite to debug this with all of that in there

**Comment by wghglory** [comment]
I downloaded your stackbitz repo and `npm run build`, which reproduced the issue. Did you try to build?

**Comment by ashleyryan** [comment]
Ah sorry, I was only running `npm run dev`

Ok, I figured it out. You need to add the `@rollup/plugin-node-resolve` module to your vite config: https://stackblitz.com/edit/vitejs-vite-xcjfsz?file=package.json,vite.config.js&terminal=build

**Comment by ashleyryan** [comment]
There are a lot of changes in v6 and a lot of internal refactoring - most of those changes were made before my time. I can't say for sure, but as the error message indicates, that file (and similar ones) uses an import from the package instead of a relative file import. That may be new in v6

**Comment by wghglory** [comment]
In v5.6.4, there's no need for `@rollup/plugin-node-resolve` to make a successful build. And I checked the file used an import from the package just like v6. So that's why I wonder what underneath causes the failure. I just didn't figure out the differences, and why the same format outputs the different results.

**Comment by wghglory** [comment]
In v5.7.2, the build error can be reproduced.
