### ISSUE TITLE
GitHub Disscussion section not activated

### ISSUE THREAD

**Issue by wokis** [vmware-clarity/core#12]
## Describe the bug

The [GitHub Discussion section](https://github.com/vmware-clarity/core/discussions) is not activated for this GitHub project and going to the page linked in the README gives a HTTP 404 error.

## How to reproduce

1.  Go to https://github.com/vmware-clarity/core/discussions as linked from the README under the Support section

## Expected behavior

The GitHub Discussion section is available.

**Comment by bbogdanov** [comment]
Hi @wokis,

Thank you for bringing our attention on this!

GitHub discussions are enabled and ready to use.

Have a wonderful Thursday!
