### ISSUE TITLE
Datalist control does not respect clrLabelSize value above 2 in horizontal or compact layouts

### ISSUE THREAD

**Issue by arcmodo** [vmware-clarity/core#128]
## Describe the bug

_When specifying clrLabelSize > 2 in a compact or horizontal layout, the datalist component is ignoring clrLabelSize._

## How to reproduce

_[Clarity Angular v13 and Core v6 Stackblitz](https://stackblitz.com/edit/clarity-light-theme-clr13-cds6-jeqc96)._

1.  In a basic Clarity Core/Angular app, set your form clrLayout="compact", "horizontal" or default and clrLabelSize="4"
2.  Add various controls such as input, select, etc., but be sure to include the datalist control
3. All controls will properly respect clrLabelSize="4" for layout, except for the datalist control

## Expected behavior

_The datalist control should respect the clrLabelSize value of 4_

## Versions

**Clarity project:**

- [x] Clarity Core
- [ ] Clarity Angular/UI

**Clarity version:**

- [ ] v5.x
- [x] v6.x

**Framework:**

- [x] Angular
- [ ] React
- [ ] Vue
- [ ] Other:

**Framework version:**
Angular v13

**Device:**

- Type: [Dell Notebook]
- OS: [Windows 10]
- Browser: [Edge (Chromium)]
- Version: [103]

## Additional notes

_This is an issue in Edge 103 and Chrome 103. Note from one of our developers, "I noticed in Clarity source code that the label columns were increased from 2 to 4 for most of the form controls except the datalist. Before the change, label was given 2 columns width and form control 10 columns. After the change, it is label 4 columns and form control 8 columns, except for datalist which appears to remain at 2 columns."_

![image](https://user-images.githubusercontent.com/13840268/180920491-501dc12f-6680-447f-b2e6-c453f4f7dec4.png)

**Comment by ashleyryan** [comment]
Clarity Core has no knowledge of clr/ui (the clr prefix you're mentioning). It does not, and will not, respect Clarity NG or Clr/ui properties. It's recommended to switch your whole form to Core, if something isn't working as expected
