### ISSUE TITLE
Form component not worked as expected

### ISSUE THREAD

**Issue by ray-sh** [vmware-clarity/core#132]
## Describe the bug

Try the form component in index.html and the form don't displabed as expected

## How to reproduce
```
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">
  <title> Index</title>
  <meta content="" name="description">
  <meta content="" name="keywords">
  <link rel="stylesheet" href="https://unpkg.com/@clr/ui/clr-ui.min.css" />
</head>
<body>
    <form clrForm>
        <clr-input-container>
          <label>Field 1 label</label>
          <input clrInput type="text" name="example" />
        </clr-input-container>
        <clr-input-container>
          <label>Field 2 label</label>
          <input clrInput type="text" name="example" />
        </clr-input-container>
      </form>
</body>
</html>
```
## Expected behavior

https://storybook.clarity.design/?path=/docs/forms-form--default

## Versions
**Clarity project:**
Clarity Core 
latest

**Framework:**
No framework

- Type: MacBook
- OS: iOS
- Browser Firefox
103.0 (64-bit)

**Comment by ashleyryan** [comment]
We've moved our websites around and that is now the ng-clarity forms page.

This is the correct url for Core forms: https://storybook.core.clarity.design/?path=/story/forms-getting-started--page
