### ISSUE TITLE
Feature Request: DataGrid for react

### ISSUE THREAD

**Issue by dionysius** [vmware-clarity/core#139]
The [Datagrid feature](https://clarity.design/documentation/datagrid/structure) seems not to be available in the [react project](https://github.com/vmware-clarity/core/tree/main/projects/react/src)

**Comment by hippee-lee** [comment]
@dionysius - it looks like you are looking for this: https://github.com/vmware-clarity/core/tree/main/projects/react/src/grid

**Comment by ashleyryan** [comment]
Unfortunately, we don’t support any datagrid in Clarity Core at the moment. While we do have some source code for it, it’s not exported for use in React. 

Our recommendation at this time is to find an alternative datagrid solution. Some react teams are using ag grid.
