### ISSUE TITLE
Empty .svg file

### ISSUE THREAD

**Issue by beaker1977** [vmware-clarity/core#238]
The svg files for icons script-execute and script-schedule are empty.

**Comment by kevinbuhmann** [comment]
We need to audit https://github.com/vmware/clarity-assets/tree/master/icons for missing icons.

**Comment by beaker1977** [comment]
A possibly related issue. The bar-chart and line-chart icons (and perhaps all chart icons) don't render properly, at least when used in the <clr-vertical-nav> component.  Two issues:

1. The icon abuts right up against the text instead of a single space gap.
2. The icon disappears when the nav is collapsed. 

My code:

<clr-vertical-nav  [clrVerticalNavCollapsible]="true" [(clrVerticalNavCollapsed)]="collapse">
     ...
<a clrVerticalNavLink routerLink="./stats" routerLinkActive="active"><cds-icon shape="bar-chart" size="24"></cds-icon>Stats</a>
     ...
</clr-vertical-nav>

See attached screen shots 

![nav issue](https://github.com/vmware-clarity/core/assets/27329476/aa8ff1ad-3305-4a09-b9bb-d713ff320e5e)

**Comment by kevinbuhmann** [comment]
No, that's unrelated. Please open a separate issue.

**Comment by beaker1977** [comment]
What's the status of new icon files? They are still empty when I download them and this wasn't addressed in issue 693.

**Comment by kevinbuhmann** [comment]
> What's the status of new icon files? They are still empty when I download them and this wasn't addressed in issue 693.

I have just merged a fix to the website. It is deploying now. It will now generated the icon directly from the selected `cds-icon` element instead of relying on the svg file existing in the assets repo.

**Comment by beaker1977** [comment]
Close but no cigar.  A new svg file was generated but it renders the icon for Event, not Script-execute. If you look at the code in the svg file it matches the code in the Event svg file.

![image](https://github.com/vmware-clarity/core/assets/27329476/6baf7f6c-73cc-4bbf-8404-291f26a8feb6)

**Comment by kevinbuhmann** [comment]
I get the correct svg when I download the `script-execute` icon on https://core.clarity.design/foundation/icons/shapes/.

I am not sure what the code is for that screenshot, so I cannot diagnose it.
