### ISSUE TITLE
Allow more CSS custom properties on `cds-accordion-header`

### ISSUE THREAD

**Issue by yuhsianw** [vmware-clarity/core#278]
_Please review our [Contribution guide](https://github.com/vmware-clarity/core/blob/main/docs/CONTRIBUTING.md) for more details about how to contribute effectively._

## Summary

_Describe the change or feature in detail. Try to answer the following questions._

- What is the change?

  Add `--box-shadow`, `--icon-visibility`, and `--icon-margin` CSS custom properties to `cds-accordion-header`.

- Why should it go in Clarity?

  This will allow Clarity users to extend the [Clarity Core Accordion](https://storybook.core.clarity.design/?path=/docs/components-accordion--page) and build a stepper component with a look and feel that matches the [Clarity Angular Stepper](https://storybook.clarity.design/?path=/story/stepper-stepper--default).

- Does this change impact existing behaviors? If so how?

  It will not change existing behaviors.

- If this change introduces a new behavior, is this behavior accessible?

  N/A.

## Use case

_Provide some specific details about how this change would improve your application and use case._
The added CSS custom properties will allow styling the Core accordion to match the Angular Stepper:
- `--box-shadow` for adding panel status indicator color block on the left of the panel header

  <img width="407" alt="Screenshot 2023-11-14 at 23 24 14" src="https://github.com/vmware-clarity/core/assets/30135709/7481c8ba-9754-4779-9987-5f81a8d18e41">

- `--icon-visibility` for hiding the `cds-button-expand` in inactive/disabled panels

  <img width="422" alt="Screenshot 2023-11-14 at 23 24 54" src="https://github.com/vmware-clarity/core/assets/30135709/b59944a5-7322-450e-be0d-9b9455a62d37">

- `--icon-margin` for aligning the `cds-button-expand` to the top 

  <img width="446" alt="Screenshot 2023-11-14 at 23 25 16" src="https://github.com/vmware-clarity/core/assets/30135709/967fe542-961b-4aaf-9478-11042d058b2b">

## Examples

_If possible, show examples of the change. You may create one yourself, or link to external sites that have the idea. It can also be very useful to prototype the idea in isolation outside of Clarity with a [Stackblitz example](https://stackblitz.com/@clr-team)._

## API

_Describe the intended API for the feature you want to add. This would include:_

- CSS classes and DOM structure for pure static UI contribution, and inputs/outputs, components, directives, services, or anything that is exported publicly for Angular contributions.

  Add `--box-shadow`, `--icon-visibility`, and `--icon-margin` CSS custom properties to `cds-accordion-header`.

- Examples of code snippets using this new feature.

  ```css
  .header {
    --icon-margin: var(--cds-global-space-3) 0 auto 0;
  }

  .panel.inactive .header {
    --box-shadow: inset var(--cds-global-space-5) 0 0 var(--cds-alias-status-neutral-tint);
    --icon-visibility: hidden;
  }
  ```
- Note very clearly if anything **might** be a breaking change.

  No breaking change.

_In the case of bug fixes or internal changes, there will most likely be no API changes._

## Implementation plan

_Describe how you plan to implement the feature, answering questions among the following or anything else you deem relevant._

- What parts of the code are affected?

  See https://github.com/vmware-clarity/core/pull/279

- Will you introduce new services, components or directives?

  No.

- Can you describe the basic flow of information between classes?

  N/A.

- Does this introduce asynchronous behaviors?

  No.

- Will you need to refactor existing Clarity code?

  No.

- Will reasonable performance require optimizations?

  No.

- Will it need to access native elements (and be incompatible with server-side rendering)?

  N/A.

- ...

## Conclusion

_Describe how long you expect it to take to implement, what help you might need, and any other details that might be helpful. Don't worry, this is obviously non-contractual. 😛_
The change is implemented in https://github.com/vmware-clarity/core/pull/279. Looking for reviews and approvals.

**Comment by williamernest** [comment]
Resolved with #279
