### ISSUE TITLE
Feedback on documentation site is broken

### ISSUE THREAD

**Issue by squidjam** [vmware-clarity/core#317]
## Describe the bug

![image](https://github.com/vmware-clarity/core/assets/537422/e30d24cc-b96b-4ad6-a5ca-913be80ed104)
## How to reproduce

Write feedback on any of the documentation site pages

1.  Go to https://storybook.js.org/docs/api/arg-types#defaultvalue
2.  Click on 'Was this page useful?' thumb down icon
3.  Write your feedback
4. Click submit
5.  See error

## Expected behavior

Feedback should be successfully submitted

## Versions

**Clarity project:**

- [x] Clarity Core
- [ ] Clarity Angular/UI

**Clarity version:**

- [ ] v5.x
- [ ] v6.x
- [ ] v7.x
- [x] v8.x

**Framework:**

- [ ] Angular
- [ ] React
- [ ] Vue
- [x] Other: documentation site is framework agnostic

**Framework version:**
N/A

**Device:**

- Type: Dell laptop
- OS: windows
- Browser chrome
- Version latest

## Additional notes

_Add any other notes about the problem here._

**Comment by kevinbuhmann** [comment]
This is the Clarity Core repo, not the Storybook repo.
