### ISSUE TITLE
Minor version introduces breaking changes to the build

### ISSUE THREAD

**Issue by squidjam** [vmware-clarity/core#318]
## Describe the bug

a deprecation for default value means the rewrite of a lot of documentation. Minor revisions are not supposed to bring breaking changes.
![image](https://github.com/vmware-clarity/core/assets/537422/bcbd2c21-217f-4207-ae9c-9bda62c363bf)

## How to reproduce

Have defaultValue set up on your storybook stories, upgrade to 8.1, see it break when building.

Described them above

## Expected behavior

Minor upgrades should not bring breaking changes or deprecations that break the build.

## Versions

**Clarity project:**

- [x] Clarity Core
- [ ] Clarity Angular/UI

**Clarity version:**

- [ ] v5.x
- [ ] v6.x
- [ ] v7.x
- [x] v8.x

**Framework:**

- [ ] Angular
- [x] React
- [ ] Vue
- [ ] Other:

**Framework version:**
React 18.2.0

**Device:**

- Type: dell laptop
- OS: windows
- Browser chrome
- Version latest

## Additional notes

why would you push a deprecation for a feature that would break the build on a minor update?
are you aware that now all our builds require to deal with this unforeseen change that cannot be planned?
please, think about this changes and review how SEMVER works.

**Comment by kevinbuhmann** [comment]
>Have defaultValue set up on your storybook stories, upgrade to 8.1, see it break when building.

Is this a Clarity Core issue or a Storybook issue? We haven't released a version 8.1 of Clarity Core.

**Comment by squidjam** [comment]
Apparently I managed to send reports to the wrong repository, my apologies
