### ISSUE TITLE
CdsPaginationButton: Disabled button has non-disabled styling

### ISSUE THREAD

**Issue by astorije-vmware** [vmware-clarity/core#84]
## Describe the bug

In Clarity v6, when using `<CdsPaginationButton action="first" aria-label="go to first" disabled></CdsPaginationButton>`, the button is correctly disabled and has the disabled cursor icon, but the regular (i.e. non-disabled) styling:

<img width="147" alt="Screen Shot 2022-06-03 at 6 42 47 PM" src="https://user-images.githubusercontent.com/90871916/171963514-cdab6b23-f408-4d79-ab6f-a9333a4acf94.png">

I do notice that Clarity's Storybook looks fine, so it may be a React wrapper bug only: https://clarity.design/storybook/core/?path=/story/components-pagination--page

## How to reproduce

See https://codesandbox.io/s/pagination-button-styling-bug-6tzc7x?file=/src/App.tsx

## Expected behavior

<img width="158" alt="Screen Shot 2022-06-03 at 6 44 40 PM" src="https://user-images.githubusercontent.com/90871916/171963615-f9048690-57ee-4872-af78-679b3bec5c6c.png">

## Versions

**Clarity project:**

- [x] Clarity Core
- [ ] Clarity Angular/UI

**Clarity version:**

- [ ] v5.x
- [x] v6.0.1

**Framework:**

- [ ] Angular
- [x] React
- [ ] Vue
- [ ] Other:

**Framework version:**
React 17

**Device:**

- OS: MacOS
- Browser Chrome

**Comment by ashleyryan** [comment]
It's not a react-only bug - for some reason the storybook is serving an old version of the library. 

It looks like it broke with this PR: https://github.com/vmware-clarity/core/pull/52

Looking into it.
